Repository deeprob-org/deeprob-kit, pull requests merged in 2021-10, with the labels that each got.

#4 Efficient algorithms for column and row splitting
  deeprob/spn/learning/splitting/cluster.py
  deeprob/spn/learning/splitting/cols.py
  deeprob/spn/learning/splitting/entropy.py
  deeprob/spn/learning/splitting/gini.py
  deeprob/spn/learning/splitting/gvs.py
  deeprob/spn/learning/splitting/rows.py
  deeprob/utils/__init__.py
  deeprob/utils/statistics.py
  experiments/spn.py
Labels: enhancement

#18 PR for Issue #11
  benchmark/clt_queries.py
  examples/clt_plot.py
  examples/clt_queries.py
  examples/clt_to_spn.py
  examples/dgcspn_mnist.py
  examples/dgcspn_olivetti.py
  examples/maf_cifar10.py
  examples/naive_model.py
  examples/nvp1d_moons.py
  examples/nvp2d_cifar10.py
  examples/nvp2d_mnist.py
  examples/ratspn_mnist.py
  examples/sklearn_interface.py
  examples/spn_clt_em.py
  examples/spn_custom_leaf.py
  examples/spn_latent_mnist.py
  examples/spn_moments.py
  examples/spn_plot.py
Labels: good first issue

#21 Fixed most Pylint errors
  deeprob/flows/layers/autoregressive.py
  deeprob/flows/layers/coupling.py
  deeprob/flows/layers/densenet.py
  deeprob/flows/layers/resnet.py
  deeprob/flows/models/base.py
  deeprob/flows/models/maf.py
  deeprob/flows/models/realnvp.py
  deeprob/flows/utils.py
  deeprob/spn/algorithms/evaluation.py
  deeprob/spn/algorithms/gradient.py
  deeprob/spn/algorithms/inference.py
  deeprob/spn/algorithms/sampling.py
  deeprob/spn/algorithms/structure.py
  deeprob/spn/layers/dgcspn.py
  deeprob/spn/layers/ratspn.py
  deeprob/spn/learning/em.py
  deeprob/spn/learning/leaf.py
  deeprob/spn/learning/learnspn.py
  deeprob/spn/learning/splitting/cluster.py
  deeprob/spn/learning/splitting/cols.py
  deeprob/spn/learning/splitting/entropy.py
  deeprob/spn/learning/splitting/gini.py
  deeprob/spn/learning/splitting/gvs.py
  deeprob/spn/learning/splitting/random.py
  deeprob/spn/learning/splitting/rdc.py
  deeprob/spn/learning/splitting/rows.py
  deeprob/spn/learning/wrappers.py
  deeprob/spn/learning/xpc.py
  deeprob/spn/models/dgcspn.py
  deeprob/spn/models/ratspn.py
  deeprob/spn/models/sklearn.py
  deeprob/spn/structure/cltree.py
  deeprob/spn/structure/io.py
  deeprob/spn/structure/leaf.py
  deeprob/spn/structure/node.py
  deeprob/spn/utils/partitioning.py
  deeprob/spn/utils/validity.py
  deeprob/torch/base.py
  deeprob/torch/callbacks.py
  deeprob/torch/constraints.py
  deeprob/torch/datasets.py
  deeprob/torch/initializers.py
  deeprob/torch/routines.py
  deeprob/torch/transforms.py
  deeprob/torch/utils.py
  deeprob/utils/__init__.py
  deeprob/utils/data.py
  deeprob/utils/graph.py
  deeprob/utils/random.py
  deeprob/utils/region.py
  deeprob/utils/statistics.py
  pylintrc
Labels: bug
